#!/bin/bash

scan-build \
-enable-checker alpha.cplusplus.NewDeleteLeaks \
-enable-checker alpha.deadcode.IdempotentOperations \
-enable-checker alpha.core.BoolAssignment \
-enable-checker alpha.core.CastSize \
-enable-checker alpha.core.CastToStruct \
-enable-checker alpha.core.FixedAddr \
-enable-checker alpha.core.IdenticalExpr \
-enable-checker alpha.core.PointerArithm \
-enable-checker alpha.core.PointerSub \
-enable-checker alpha.core.SizeofPtr \
-enable-checker alpha.cplusplus.VirtualCall \
-enable-checker alpha.deadcode.UnreachableCode \
-enable-checker alpha.osx.cocoa.Dealloc \
-enable-checker alpha.osx.cocoa.DirectIvarAssignment \
-enable-checker alpha.osx.cocoa.DirectIvarAssignmentForAnnotatedFunctions \
-enable-checker alpha.osx.cocoa.InstanceVariableInvalidation \
-enable-checker alpha.osx.cocoa.MissingInvalidationMethod \
-enable-checker alpha.security.ArrayBound \
-enable-checker alpha.security.ArrayBoundV2 \
-enable-checker alpha.security.MallocOverflow \
-enable-checker alpha.security.ReturnPtrRange \
-enable-checker alpha.security.taint.TaintPropagation \
-enable-checker alpha.unix.Chroot \
-enable-checker alpha.unix.MallocWithAnnotations \
-enable-checker alpha.unix.PthreadLock \
-enable-checker alpha.unix.SimpleStream \
-enable-checker alpha.unix.Stream \
-enable-checker alpha.unix.cstring.BufferOverlap \
-enable-checker alpha.unix.cstring.NotNullTerminated \
-enable-checker alpha.unix.cstring.OutOfBounds \
-enable-checker core.CallAndMessage \
-enable-checker core.DivideZero \
-enable-checker core.DynamicTypePropagation \
-enable-checker core.NonNullParamChecker \
-enable-checker core.NullDereference \
-enable-checker core.StackAddressEscape \
-enable-checker core.UndefinedBinaryOperatorResult \
-enable-checker core.VLASize \
-enable-checker core.builtin.BuiltinFunctions \
-enable-checker core.builtin.NoReturnFunctions \
-enable-checker core.uninitialized.ArraySubscript \
-enable-checker core.uninitialized.Assign \
-enable-checker core.uninitialized.Branch \
-enable-checker core.uninitialized.CapturedBlockVariable \
-enable-checker core.uninitialized.UndefReturn \
-enable-checker cplusplus.NewDelete \
-enable-checker deadcode.DeadStores \
-enable-checker llvm.Conventions \
-enable-checker security.FloatLoopCounter \
-enable-checker security.insecureAPI.UncheckedReturn \
-enable-checker security.insecureAPI.getpw \
-enable-checker security.insecureAPI.gets \
-enable-checker security.insecureAPI.mkstemp \
-enable-checker security.insecureAPI.mktemp \
-enable-checker security.insecureAPI.rand \
-enable-checker security.insecureAPI.strcpy \
-enable-checker security.insecureAPI.vfork \
-enable-checker unix.API \
-enable-checker unix.Malloc \
-enable-checker unix.MallocSizeof \
-enable-checker unix.MismatchedDeallocator \
-enable-checker unix.cstring.BadSizeArg \
-enable-checker unix.cstring.NullArg \
$*

#-enable-checker alpha.osx.cocoa.MissingSuperCall \

#-enable-checker osx.API \
#-enable-checker osx.SecKeychainAPI \
#-enable-checker osx.cocoa.AtSync \
#-enable-checker osx.cocoa.ClassRelease \
#-enable-checker osx.cocoa.IncompatibleMethodTypes \
#-enable-checker osx.cocoa.Loops \
#-enable-checker osx.cocoa.NSAutoreleasePool \
#-enable-checker osx.cocoa.NSError \
#-enable-checker osx.cocoa.NilArg \
#-enable-checker osx.cocoa.NonNilReturnValue \
#-enable-checker osx.cocoa.RetainCount \
#-enable-checker osx.cocoa.SelfInit \
#-enable-checker osx.cocoa.UnusedIvars \
#-enable-checker osx.cocoa.VariadicMethodTypes \
#-enable-checker osx.coreFoundation.CFError \
#-enable-checker osx.coreFoundation.CFNumber \
#-enable-checker osx.coreFoundation.CFRetainRelease \
#-enable-checker osx.coreFoundation.containers.OutOfBounds \
#-enable-checker osx.coreFoundation.containers.PointerSizedValues \

#-enable-checker debug.ConfigDumper \
#-enable-checker debug.DumpCFG \
#-enable-checker debug.DumpCallGraph \
#-enable-checker debug.DumpCalls \
#-enable-checker debug.DumpDominators \
#-enable-checker debug.DumpLiveVars \
#-enable-checker debug.DumpTraversal \
#-enable-checker debug.ExprInspection \
#-enable-checker debug.Stats \
#-enable-checker debug.TaintTest \
#-enable-checker debug.ViewCFG \
#-enable-checker debug.ViewCallGraph \
#-enable-checker debug.ViewExplodedGraph \
